sudo: false
language: node_js
branches:
  only:
    - master
cache:
  yarn: true
  directories:
    - node_modules
node_js:
  - 8
services:
  - mongodb
script:
  - npm run test
after_success:
  - npm run coveralls